name: Metrics

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  metrics:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Generate isometric contribution calendar
        uses: lowlighter/metrics@latest
        with:
          user: HamzaTaif
          token: ${{ secrets.METRICS_TOKEN }}

          filename: metrics.plugin.isocalendar.svg

          base: ""

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year

          config_timezone: Asia/Karachi
